name: Build .NET Framework Console App
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.x.x'

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build the project
      run: msbuild /p:Configuration=Release /p:OutputPath=output

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ImportTablePatcher
        path: output/ImportTablePatcher.exe
